### PR TITLE
Remove arched bits from version.cmake-file

### PR DESCRIPTION
**Pull request by besser82**
Since putting arch-dependent file into `/usr/share` is a violation of the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure), I've made some small changes in CMake to put the generated arch-dependent files into the proper arch-dependent CMake-dir.

I think this will make distribution-maintainers more happy.

### CODE REVIEW

**Comment by agaida** [comment]
if it works it is cleaner and GTM - but it will not make me happy - i would be happy if cmake would not generate arch dependend text files - esp. when the only arch dependend part is a braindead and not needed Arch check mentioned on #12 :P 

Don't get me wrong - but that would not improve the situation much.

**Comment by lupinix** [comment]
We will see, I applied the patch in Fedora as I have to be FHS conform. So I'll be the one who gets the failures :D

**Comment by agaida** [comment]
if it is in the search path i have no problems with the changes - as i wrote it is cleaner. but i need packages for each arch - ok only 20 right now. :P

**Comment by besser82** [comment]
With the current change, all arch-dependent bits are removed from the `version.cmake`-file and the whole thing is arch-independent, now.

**Comment by agaida** [comment]
@besser82 - lovely

because of:  https://buildd.debian.org/status/package.php?p=lxqt-build-tools - waiting for arch-builds over a certain amount of time sucks a lot - now at least i'm very happy :D

**Comment by besser82** [comment]
@agaida I'm glad! You're Welcome  =)

**Comment by luis-pereira** [comment]
Thanks @besser82

**Comment by besser82** [comment]
@agaida @luis-pereira Ready to merge?  Anyone?

**Comment by agaida** [comment]
patience - have build nearly all packages with it - so far all things are fine, but please let me finish first :)

**Comment by agaida** [comment]
GTM - tested with amd64 and i386 complete rebuild without any regressions noticed.

**Comment by besser82** [comment]
@agaida Great!  Thank you ^_^

**Pull request merged**
