### PR TITLE
Require Qt 5.7.1

### PR DESCRIPTION
**Pull request by agaida**
5.7 would be ok too featurewise, but was to buggy - so they put out 5.7.1 really fast. We should require 5.7.1 when we don't want possible regressions because of Qt.

### CODE REVIEW

**Comment by agaida** [comment]
Upps - Qt 5.7 was nearly fine - anyways, distributions should use 5.7.1

**Comment by palinek** [comment]
GTM

**Comment by palinek** [comment]
Actually... with this we probably should increase the `LXQT_BUILD_TOOLS_PATCH_VERSION` also and in all "Drop foreach" PRs require the new `lxqt-build-tools`...

What do you think?

**Comment by tsujan** [comment]
> Actually... with this we probably should increase the LXQT_BUILD_TOOLS_PATCH_VERSION

That's correct, IMO.

**Comment by luis-pereira** [comment]
Yeap. `lxqt-build-tools` patch version should be increased.

**Comment by tsimonq2** [comment]
:+1: 

By the time 0.13 is released, the latest LTS of Ubuntu will have 5.9, so as long as we can keep with that for the next +/- 2 years, I'm gucci.

**Comment by yan12125** [comment]
I think a 0.4.1 tag is necessary for the second commit? Not sure if it's possible to add a tag for old commits.

**Comment by agaida** [comment]
We will tag it 0.4.1 with the release - until it isn't released it isn't important, only for those who running latest git - and in that case it is far more important to update packages in the right build order, a tag wouldn't change much.

**Comment by yan12125** [comment]
Thanks I got it. I was wondering whether I should ask lxqt-*-git package maintainers to use lxqt-build-tools-git or not.

**Pull request merged**
