### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by pmattern** [comment]
PR makes a valid point but I think an additional section like "Distribution packagers" proposed right now doesn't make sense and the diff output shouldn't be included in an informational file like this either.
Rather I'd propose to complement section "Compiling sources" with a phrase like
> Please note the repository does not comprise binary files yet architecture specific ones. So packages should not be labeled as architecture independent.

**Comment by agaida** [comment]
@luis-pereira what do you think - can we prevent the generation of theses tests? They are nuts in this place to be honest. (Or at least i can't see any reason to check 32/64bitness there)

**Comment by luis-pereira** [comment]
@agaida @pmattern 
Those tests are generated by the standard `write_basic_package_version_file()`. They are pretty much part of the CMake package version handling.
It can be disabled, but a custom version package checking would have to be written.
How is KDE extra-cmake-modules handled in debian ? They have the same issue, for sure.

**Comment by agaida** [comment]
To be honest - i don't care if a Sourcecode creates one, two or twenty binaries - as long these created binaries work reliable - and if it is cmake builtin functionality than we should avoid working against cmake. Btw - you asked about extra-cmake-modules in debian - they are depend on the build arch too.

That said - we should place a hint to the packagers into the readme because it is not obvious that a simple set of textfiles depends on the build architecture - i run into that, the guy who reviews my packaging run into the assumption - so there should be a warning.

**Pull request closed without merging**
