### PR TITLE
Make lxqt-build-tools be usable

### PR DESCRIPTION
**Pull request by luis-pereira**
Now it's an CMake package that can be used by others.

Companion PR's:
https://github.com/lxde/liblxqt/pull/109
https://github.com/lxde/libfm-qt/pull/46
https://github.com/lxde/lximage-qt/pull/73
https://github.com/lxde/lxqt-about/pull/35
https://github.com/lxde/lxqt-admin/pull/41
https://github.com/lxde/lxqt-qtplugin/pull/15

To be continued......

### CODE REVIEW

**Comment by agaida** [comment]
* liblxqt build fine in amd64 and i386

**Comment by luis-pereira** [comment]
https://github.com/lxde/obconf-qt/pull/23
https://github.com/lxde/pavucontrol-qt/pull/18
https://github.com/lxde/compton-conf/pull/35
https://github.com/lxde/qterminal/pull/270
https://github.com/lxde/pcmanfm-qt/pull/403

**Comment by agaida** [comment]
@luis-pereira - we should merge and release the build tools now - the package works fine.

**Comment by luis-pereira** [comment]
@agaida There is some stuff to be handled. Some compile definitions location and some finishing the module centralization (portable headers and .pc files)
I'm away now. Will do it Monday

**Comment by agaida** [comment]
Cool - right now all packages build with the current state - except the translations
```
## set temporary - dirty hack
set(LXQT_SHARE_DIR "${CMAKE_INSTALL_FULL_DATAROOTDIR}/lxqt")
set(LXQT_TRANSLATIONS_DIR "${LXQT_SHARE_DIR}/translations")
## dirty hack end
```
^^  this does the trick in a very hacky manner directly in the CMakeLists.txt of lxqt-l10n

**Comment by agaida** [comment]
Edit: forget about the hack, not sufficient

**Comment by luis-pereira** [comment]
- libsystat https://github.com/lxde/libsysstat/pull/15

**Comment by agaida** [comment]
@luis-pereira: can we merge make-it-work in the current state - it has not be to be complete or 100% bugfree in corner cases, but i run out of time - the alternative is that we will have to maintain both implementations for debian/ubuntu at least for the next 2-3 years.

**Comment by luis-pereira** [comment]
@agaida That would be terrible. I'm pushing the button. Improvements can be made later on.

**Pull request merged**
