### PR TITLE
Move lxde version

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by agaida** [comment]
@luis-pereira any objections?

**Comment by luis-pereira** [comment]
@agaida I'm a bit out of context. What's the reasoning ?

**Comment by agaida** [comment]
we talked about after the last release - it is not wise to hard wire the version of liblxqt (and so the lxqt version) in the build tools - each version bump, patch version etc would need another change in the build tools and a new release of it - if we have done our job right only with on digit changed.

**Comment by luis-pereira** [comment]
@agaida Now I remember. It's Ok. But @palinek is right. `lxqt-build-tools` need to be addressed.
And every component that depends on `lxqt-build-tools` and not `liblxqt` needs to be checked.

**Comment by agaida** [comment]
it's not that hard - every LXQt-component that create a binary (and which can use a version information) depends on liblxqt - the only components that not depend on liblxqt are the themes, translation and the qt-plugin. All other components that use the build tools are not part of lxqt.

**Comment by palinek** [comment]
GTM

**Comment by luis-pereira** [comment]
@agaida You are on top of it. 
GTM.

**Pull request merged**
