### PR TITLE
Add config vars module

### PR DESCRIPTION
**Pull request by luis-pereira**
To be merged after https://github.com/lxde/lxqt-build-tools/pull/3

### CODE REVIEW

**Comment by palinek** [comment]
@luis-pereira I've rebased this after I merged the #3 w/o the merge commit....

**Comment by luis-pereira** [comment]
@palinek That's fine. https://github.com/lxde/lxqt-build-tools/pull/3 was a one commit PR.

**Comment by luis-pereira** [comment]
New changes:

``` diff
@@ -74,6 +74,7 @@ configure_package_config_file(
 configure_file(
     "${CMAKE_CURRENT_SOURCE_DIR}/cmake/LXQtConfigVars.cmake.in"
     "${MODULES_INSTALL_DIR}/LXQtConfigVars.cmake"
+    @ONLY
 )
 
 
@@ -96,6 +97,7 @@ configure_package_config_file(
 configure_file(
     "${CMAKE_CURRENT_SOURCE_DIR}/cmake/LXQtConfigVars.cmake.in"
     "${CMAKE_CURRENT_BINARY_DIR}/install/LXQtConfigVars.cmake"
+    @ONLY
 )
```

**Comment by agaida** [comment]
Great, just successfully tested - GTM

**Pull request merged**
